---
abstract: 'converts a distribution to Dist::Zilla'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zooky
requires:
  App::Cmd: 0.307
  CPAN::Meta: 2.101610
  Class::MOP: 1.03
  Dist::Zilla: 4.101582
  ExtUtils::MakeMaker: 6.56
  File::Temp: 0.22
  IPC::Cmd: 0.58
  Module::Build: 0.3607
  Module::Load::Conditional: 0.38
  Module::Pluggable: 3.9
  Moose: 1.07
  MooseX::Types::Moose: 0.22
  MooseX::Types::Perl: 0.101340
  Params::Check: 0.26
  Software::License: 0.101620
  perl: 5.008005
resources:
  homepage: http://github.com/bingos/dist-zooky/tree
  repository: git://github.com/bingos/dist-zooky.git
version: 0.04
